"""Compatibility facade for runtime backend contracts and implementations."""

from gpt2giga.app._runtime_backends import (
    ConfigurableRuntimeStateBackend,
    EventFeed,
    InMemoryEventFeed,
    InMemoryRuntimeStateBackend,
    QueryableEventFeed,
    RUNTIME_RESOURCE_DESCRIPTORS,
    RuntimeBackendDescriptor,
    RuntimeBackendFactory,
    RuntimeResourceDescriptor,
    RuntimeResourceKind,
    RuntimeStateBackend,
    SqliteEventFeed,
    SqliteMapping,
    SqliteRuntimeStateBackend,
    create_runtime_backend,
    get_runtime_backend_descriptor,
    list_runtime_backend_descriptors,
    provision_runtime_resources,
    register_runtime_backend,
)

__all__ = [
    "ConfigurableRuntimeStateBackend",
    "EventFeed",
    "InMemoryEventFeed",
    "InMemoryRuntimeStateBackend",
    "QueryableEventFeed",
    "RUNTIME_RESOURCE_DESCRIPTORS",
    "RuntimeBackendDescriptor",
    "RuntimeBackendFactory",
    "RuntimeResourceDescriptor",
    "RuntimeResourceKind",
    "RuntimeStateBackend",
    "SqliteEventFeed",
    "SqliteMapping",
    "SqliteRuntimeStateBackend",
    "create_runtime_backend",
    "get_runtime_backend_descriptor",
    "list_runtime_backend_descriptors",
    "provision_runtime_resources",
    "register_runtime_backend",
]
