import json

from openai import OpenAI

api_version = "v2"
client = OpenAI(base_url=f"http://localhost:8090/{api_version}/", api_key="0")

# 1. Define a callable tool for the model
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_horoscope",
            "description": "Get today's horoscope for an astrological sign.",
            "parameters": {
                "type": "object",
                "properties": {
                    "sign": {
                        "type": "string",
                        "description": "An astrological sign like Taurus or Aquarius",
                    },
                },
                "required": ["sign"],
            },
        },
    },
]


def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."


# Create a running message list we will add to over time
messages = [{"role": "user", "content": "What is my horoscope? I am an Aquarius."}]

# 2. Prompt the model with tools defined
response = client.chat.completions.create(
    model="GigaChat-2-Max",
    tools=tools,
    messages=messages,
)

# Save the assistant tool call for subsequent requests
response_message = response.choices[0].message
messages.append(response_message.model_dump(exclude_none=True))

for tool_call in response_message.tool_calls or []:
    if tool_call.function.name == "get_horoscope":
        # 3. Execute the function logic for get_horoscope
        arguments = json.loads(tool_call.function.arguments)
        horoscope = get_horoscope(arguments["sign"])

        # 4. Provide function call results to the model
        messages.append(
            {
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": json.dumps(
                    {"horoscope": horoscope},
                    ensure_ascii=False,
                ),
            }
        )

print("Final messages:")
print(json.dumps(messages, indent=2, ensure_ascii=False))

response = client.chat.completions.create(
    model="GigaChat-2-Max",
    messages=[
        {
            "role": "system",
            "content": "Respond only with a horoscope generated by a tool.",
        },
        *messages,
    ],
    tools=tools,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + (response.choices[0].message.content or ""))
