"""Bounded local storage for files generated by upstream built-in tools."""

from __future__ import annotations

import base64
import binascii
from hashlib import sha256
from pathlib import Path
import re
from typing import Any, Mapping

MAX_GENERATED_FILE_BYTES = 25 * 1024 * 1024
GENERATED_FILES_DIR = "generated-files"
_SAFE_SEGMENT = re.compile(r"^[a-f0-9]{64}$")
_IMAGE_EXTENSIONS = {
    "image/avif": ".avif",
    "image/bmp": ".bmp",
    "image/gif": ".gif",
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}


class GeneratedFileError(ValueError):
    """Raised when generated file metadata or content is unsafe."""


def persist_generated_image(
    data_dir: str | Path,
    *,
    run_id: str,
    file_id: str,
    mime_type: str,
    content_base64: str,
) -> dict[str, Any]:
    """Decode and persist one generated image under the Harness data directory."""
    extension = _IMAGE_EXTENSIONS.get(mime_type.lower())
    if extension is None:
        raise GeneratedFileError("unsupported generated image type")
    try:
        content = base64.b64decode(content_base64, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise GeneratedFileError("generated image content is not valid base64") from exc
    if not content or len(content) > MAX_GENERATED_FILE_BYTES:
        raise GeneratedFileError("generated image size is outside the allowed range")

    run_key = _digest(run_id)
    file_key = _digest(file_id)
    filename = f"{file_key}{extension}"
    directory = generated_files_root(data_dir) / run_key
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / filename
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_bytes(content)
    temporary.replace(target)
    return {
        "id": file_id,
        "file_id": file_id,
        "filename": f"generated-{file_key[:12]}{extension}",
        "mime_type": mime_type.lower(),
        "target": "image",
        "size_bytes": len(content),
        "preview_url": f"/api/files/generated/{run_key}/{filename}",
    }


def generated_file_path(
    data_dir: str | Path,
    run_key: str,
    filename: str,
) -> Path:
    """Resolve a hashed generated-file URL without allowing path traversal."""
    suffix = Path(filename).suffix.lower()
    file_key = Path(filename).stem
    if not _SAFE_SEGMENT.fullmatch(run_key) or not _SAFE_SEGMENT.fullmatch(file_key):
        raise GeneratedFileError("invalid generated file path")
    if suffix not in set(_IMAGE_EXTENSIONS.values()):
        raise GeneratedFileError("unsupported generated file extension")
    root = generated_files_root(data_dir)
    resolved = (root / run_key / filename).resolve()
    if not resolved.is_relative_to(root):
        raise GeneratedFileError("generated file escapes its storage root")
    return resolved


def generated_files_root(data_dir: str | Path) -> Path:
    """Return the resolved generated-file storage root."""
    return Path(data_dir).expanduser().resolve() / GENERATED_FILES_DIR


def generated_image_metadata(value: Mapping[str, Any]) -> tuple[str, str] | None:
    """Return ``(file_id, mime_type)`` for a supported generated image."""
    file_id = value.get("id")
    mime_type = value.get("mime") or value.get("mime_type")
    target = value.get("target")
    if not isinstance(file_id, str) or not file_id:
        return None
    if not isinstance(mime_type, str) or mime_type.lower() not in _IMAGE_EXTENSIONS:
        return None
    if target not in {None, "image"}:
        return None
    return file_id, mime_type.lower()


def _digest(value: str) -> str:
    return sha256(value.encode("utf-8")).hexdigest()
