x-gpt2giga-common: &gpt2giga-common
  image: ghcr.io/ai-forever/gpt2giga:latest
  restart: unless-stopped
  build:
    context: ../..
    dockerfile: Dockerfile
    args:
      PYTHON_VERSION: "3.13"
  env_file:
    - ${GPT2GIGA_COMPOSE_ENV_FILE:-../../.env}
  container_name: gpt2giga
  environment:
    GPT2GIGA_HOST: "0.0.0.0"
    GPT2GIGA_CONTROL_PLANE_DIR: "/var/lib/gpt2giga/control"
  volumes:
    - gpt2giga-data:/var/lib/gpt2giga

services:
  gpt2giga-prod:
    <<: *gpt2giga-common
    profiles: ["PROD"]
    environment:
      GPT2GIGA_MODE: "PROD"
      GPT2GIGA_HOST: "0.0.0.0"
      GPT2GIGA_CONTROL_PLANE_DIR: "/var/lib/gpt2giga/control"
    ports:
      - "127.0.0.1:${GPT2GIGA_PORT:-8090}:${GPT2GIGA_PORT:-8090}"

  gpt2giga-dev:
    <<: *gpt2giga-common
    profiles: ["", "DEV"]
    environment:
      GPT2GIGA_MODE: "DEV"
      GPT2GIGA_HOST: "0.0.0.0"
      GPT2GIGA_CONTROL_PLANE_DIR: "/var/lib/gpt2giga/control"
    ports:
      - "${GPT2GIGA_PORT:-8090}:${GPT2GIGA_PORT:-8090}"

volumes:
  gpt2giga-data:
