"""Built-in Fusion presets used when env presets are not supplied."""

from __future__ import annotations

from gpt2giga.models.config import FusionPresetSettings


def built_in_fusion_presets() -> dict[str, FusionPresetSettings]:
    """Return fresh built-in Fusion preset objects."""
    return {
        "general": FusionPresetSettings(
            analysis_models=["GigaChat-2-Max", "GigaChat-2-Pro"],
            judge_model="GigaChat-2-Max",
            panel_roles=["planner", "critic"],
            temperature=0.2,
            max_completion_tokens=3072,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="off",
        ),
        "code-budget": FusionPresetSettings(
            analysis_models=["GigaChat-2-Pro", "GigaChat-2-Max"],
            judge_model="GigaChat-2-Max",
            panel_roles=["implementer", "reviewer"],
            temperature=0.2,
            max_completion_tokens=3072,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="schema_only",
        ),
        "code-high": FusionPresetSettings(
            analysis_models=[
                "GigaChat-3-Ultra",
                "GigaChat-2-Max",
                "GigaChat-2-Pro",
            ],
            judge_model="GigaChat-3-Ultra",
            panel_roles=["architect", "implementer", "reviewer"],
            temperature=0.2,
            max_completion_tokens=4096,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            min_successful_panels=1,
            timeout_seconds=180.0,
            tools_mode="schema_only",
        ),
        "accuracy-ultra-selector": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            panel_roles=["solver"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=True,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=12000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="off",
        ),
        "accuracy-ultra-verifier": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            final_model="GigaChat-3-Ultra",
            panel_roles=["verifier"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=True,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            max_panel_output_chars=4000,
            max_total_panel_output_chars=8000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="off",
        ),
        "code-agent-safe": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra", "GigaChat-2-Max"],
            judge_model="GigaChat-3-Ultra",
            final_model="GigaChat-3-Ultra",
            panel_roles=["solver", "reviewer"],
            temperature=0,
            max_completion_tokens=8192,
            include_direct_candidate=True,
            return_selected_candidate=False,
            invocation_mode="outer_auto",
            decision_mode="tool_result",
            prompt_mode="minimal",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=16000,
            min_successful_panels=1,
            timeout_seconds=180.0,
            tools_mode="schema_only",
        ),
        "force-selector": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            panel_roles=["solver"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=True,
            invocation_mode="force",
            decision_mode="selector",
            prompt_mode="minimal",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=12000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="off",
        ),
        "force-benchmark-selector": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            direct_model="GigaChat-3-Ultra",
            panel_roles=["solver"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=True,
            invocation_mode="force",
            decision_mode="selector",
            prompt_mode="minimal",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=12000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="off",
        ),
        "force-benchmark-selector-tools": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            direct_model="GigaChat-3-Ultra",
            final_model="GigaChat-3-Ultra",
            panel_roles=["solver"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=True,
            invocation_mode="force",
            decision_mode="selector",
            prompt_mode="minimal",
            direct_tool_call_policy="selector",
            post_tool_mode="fusion_continuation",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=12000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="schema_only",
        ),
        "verified-tool-loop-ultra": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra"],
            judge_model="GigaChat-3-Ultra",
            direct_model="GigaChat-3-Ultra",
            final_model="GigaChat-3-Ultra",
            panel_roles=["verifier"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=True,
            return_selected_candidate=False,
            invocation_mode="force",
            decision_mode="action",
            prompt_mode="minimal",
            candidate_stage_order="direct_then_verify",
            direct_tool_call_policy="verify_before_return",
            post_tool_mode="verified_continuation",
            max_panel_output_chars=4000,
            max_total_panel_output_chars=8000,
            min_successful_panels=1,
            timeout_seconds=120.0,
            tools_mode="schema_only",
            max_client_tool_rounds=8,
        ),
        "force-synthesize": FusionPresetSettings(
            analysis_models=["GigaChat-3-Ultra", "GigaChat-2-Max"],
            judge_model="GigaChat-3-Ultra",
            final_model="GigaChat-3-Ultra",
            panel_roles=["solver", "reviewer"],
            temperature=0,
            max_completion_tokens=None,
            include_direct_candidate=False,
            return_selected_candidate=True,
            invocation_mode="force",
            decision_mode="synthesize",
            prompt_mode="full",
            max_panel_output_chars=6000,
            max_total_panel_output_chars=16000,
            min_successful_panels=1,
            timeout_seconds=180.0,
            tools_mode="schema_only",
        ),
    }


def get_fusion_presets(
    custom_presets: dict[str, FusionPresetSettings],
) -> dict[str, FusionPresetSettings]:
    """Merge built-in presets with user presets."""
    presets = built_in_fusion_presets()
    presets.update(custom_presets)
    return presets
